# Embeds a binary/text file into a generated C++ source as a byte array, so
# it ends up compiled directly into the executable with no runtime file
# dependency. Invoked at BUILD time (not just configure time) via
# add_custom_command, so it re-runs whenever INPUT changes.
#
# Usage: cmake -DINPUT=<path> -DOUTPUT=<path> -DVARNAME=<identifier> -P EmbedFile.cmake
#
# Generates a .cpp defining, in namespace apr::embedded:
#   extern const unsigned char <VARNAME>_data[];
#   extern const std::size_t <VARNAME>_size;
#
# Hex-encodes the content into an array literal rather than using a raw
# string literal, deliberately - HTML/JS source can contain byte sequences
# that would collide with any raw-string delimiter we picked, and CMake
# variables containing ';' (extremely common in JS/CSS) risk being
# reinterpreted as list separators if handled as anything other than opaque
# hex text.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VARNAME)
    message(FATAL_ERROR "EmbedFile.cmake requires -DINPUT=, -DOUTPUT=, -DVARNAME=")
endif()

file(READ "${INPUT}" hex_content HEX)
string(LENGTH "${hex_content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")

file(WRITE "${OUTPUT}" "// Auto-generated by cmake/EmbedFile.cmake from ${INPUT} - do not edit.\n")
file(APPEND "${OUTPUT}" "#include <cstddef>\n\nnamespace apr {\nnamespace embedded {\n\n")
file(APPEND "${OUTPUT}" "extern const unsigned char ${VARNAME}_data[] = {\n")

# Batch hex pairs into line buffers and flush with one file(APPEND) per
# batch, rather than one APPEND call per byte (too many I/O calls) or one
# giant in-memory string (slow to grow via repeated string(APPEND)).
set(pairs_per_line 20)
set(lines_per_flush 200)
set(line_buffer "")
set(flush_buffer "")
set(pair_count_in_line 0)
set(line_count_in_flush 0)

set(pos 0)
while(pos LESS hex_len)
    string(SUBSTRING "${hex_content}" ${pos} 2 byte_hex)
    string(APPEND line_buffer "0x${byte_hex}, ")
    math(EXPR pair_count_in_line "${pair_count_in_line} + 1")
    math(EXPR pos "${pos} + 2")

    if(pair_count_in_line EQUAL pairs_per_line OR pos GREATER_EQUAL hex_len)
        string(APPEND flush_buffer "  ${line_buffer}\n")
        set(line_buffer "")
        set(pair_count_in_line 0)
        math(EXPR line_count_in_flush "${line_count_in_flush} + 1")

        if(line_count_in_flush EQUAL lines_per_flush OR pos GREATER_EQUAL hex_len)
            file(APPEND "${OUTPUT}" "${flush_buffer}")
            set(flush_buffer "")
            set(line_count_in_flush 0)
        endif()
    endif()
endwhile()

file(APPEND "${OUTPUT}" "};\n\n")
file(APPEND "${OUTPUT}" "extern const std::size_t ${VARNAME}_size = ${byte_count};\n\n")
file(APPEND "${OUTPUT}" "} // namespace embedded\n} // namespace apr\n")

message(STATUS "Embedded ${INPUT} (${byte_count} bytes) -> ${OUTPUT}")
